name: CI - Build and Push Docker Image

on:
  push:
    branches: [main]  # Roda somente na branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t yuripaixao/hc-devops:latest .
          
      - name: Rodar container e testar rota /health 
        run: |
          docker run -d --rm --name hc-app -p 5000:5000 yuripaixao/hc-devops:latest
          sleep 5 # tempo para a aplicação subir
          #curl -f http://localhost:5000/health # comentado, como o reddis está down o retorno é 503 e vai quebrar o pipeline
          docker stop hc-app

      - name: Push da imagem para o Docker Hub
        run: |
          docker push yuripaixao/hc-devops:latest
